import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import useSWR from 'swr'
import { useEffect, useRef, useState } from 'react'
import axios from 'axios'

export default function Home() {

  const inputRef = useRef<HTMLInputElement>(null)

  const [texto, setTexto] = useState("")
  
  const postTexto = async () => {
    setTexto("CARGANDO....")
    const data = await axios.post("/api/chat", {texto: inputRef.current!.value})
    setTexto(data.data.response)
    const audioLoquendo = await axios({
      method: 'get',
      url: `/api/habla?txt=${data.data.response.split(' ').join("%20")}`, 
       //url: `/api/habla?txt=${inputRef.current!.value.split(' ').join("%20")}`, 
      responseType: "arraybuffer",
    })
    const response = audioLoquendo;
//     const blob = new Blob([response.data], { type: 'audio/mpeg' });
// console.log(blob)

   const ctx = new AudioContext();


  const audio = await ctx.decodeAudioData(response.data)

  const playSound = ctx.createBufferSource();
  playSound!.buffer! = audio;
  playSound.connect(ctx.destination);
  playSound.start(ctx.currentTime);

    //const a = new Audio("http://localhost:3000/api/habla?txt=holaxDD")
    // Crear un objeto URL para el stream
    //const audioURL = 
  // console.log(URL.createObjectURL(blob);)
  //   a.src = URL.createObjectURL(blob);

    //a.load()
   // await a.play()
    // Crear un elemento de audio en el DOM
   // const audio = document.createElement('audio');

    // Asignar la fuente del audio al stream
    //audio.src = audioURL;

    // Agregar el elemento de audio al DOM
    //document.body.appendChild(audio);

    // Reproducir el audio
    
  }
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
         CHUCK NORRIS CARAJO
         <img src="https://i.imgur.com/ZzobL3Y.jpg" alt="" />
         <input type="text" ref={inputRef}/>
         <button onClick={ev => postTexto()}>RESPONDE MIERDA</button>
         <div>{texto}</div>
      </main>
    </>
  )
}
